module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#001e2c',
        'primary-fixed': '#dae2fd',
        'on-tertiary-fixed-variant': '#004c69',
        'surface-container-lowest': '#ffffff',
        'outline': '#76777d',
        'on-primary-fixed-variant': '#3f465c',
        'primary-container': '#131b2e',
        'primary': '#000000',
        'on-surface-variant': '#45464d',
        'on-tertiary-container': '#008ebf',
        'on-secondary-fixed': '#0d1c2f',
        'error': '#ba1a1a',
        'on-secondary-container': '#57657b',
        'surface-container-highest': '#e0e3e5',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2d3133',
        'outline-variant': '#c6c6cd',
        'tertiary-container': '#001e2c',
        'primary-fixed-dim': '#bec6e0',
        'tertiary-fixed': '#c4e7ff',
        'tertiary': '#000000',
        'surface-variant': '#e0e3e5',
        'on-primary': '#ffffff',
        'secondary-container': '#d5e3fd',
        'surface-tint': '#565e74',
        'on-surface': '#191c1e',
        'secondary-fixed-dim': '#b9c7e0',
        'on-error-container': '#93000a',
        'surface-container': '#eceef0',
        'secondary': '#515f74',
        'surface-container-low': '#f2f4f6',
        'error-container': '#ffdad6',
        'surface-bright': '#f7f9fb',
        'on-error': '#ffffff',
        'secondary-fixed': '#d5e3fd',
        'surface-container-high': '#e6e8ea',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'background': '#f7f9fb',
        'on-secondary-fixed-variant': '#3a485c',
        'surface': '#f7f9fb',
        'on-primary-fixed': '#131b2e',
        'inverse-primary': '#bec6e0',
        'on-primary-container': '#7c839b',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#7bd0ff',
        'surface-dim': '#d8dadc'
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'margin-desktop': '32px',
        'density-compact': '8px',
        'margin-mobile': '16px',
        'density-comfortable': '16px',
        'unit': '4px',
        'gutter': '16px'
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'sans': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace']
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }]
      }
    },
  },
  plugins: [],
}
